[
   {
      "Slug": "acme-sa",
      "DisplayName": "Acme SA",
      "IsCompany": true,
      "CompanyName": "Acme SA",
      "Civility": null,
      "LastName": null,
      "FirstName": null,
      "Title": null,
      "Phone1": "02 02 02 02 02",
      "Phone2": null,
      "Fax": "02 02 02 02 22",
      "Email": "contact@acme.com",
      "Url": "http://www.acme.com/",
      "AddressLine1": "Batiment A1",
      "AddressLine2": "12, Boulevard des Capucines",
      "PostalCode": "13000",
      "Municipality": "Marseille",
      "Country": "France",
      "Notes": "Très bon fournisseur",
      "Tags": "Fournisseur,Local"
   },
   {
      "Slug": "charpentes-du-moulin",
      "DisplayName": "Charpentes du Moulin",
      "IsCompany": true,
      "CompanyName": "Charpentes du Moulin",
      "Civility": null,
      "LastName": null,
      "FirstName": null,
      "Title": null,
      "Phone1": "10 10 10 10 10",
      "Phone2": null,
      "Fax": null,
      "Email": "contact@charpentes-du-moulin.net",
      "Url": "http://www.charpentes-du-moulin.net/",
      "AddressLine1": "29 Chemin des Bois",
      "AddressLine2": null,
      "PostalCode": "69000",
      "Municipality": "Lyon",
      "Country": null,
      "Notes": null,
      "Tags": "Client"
   },
   {
      "Slug": "sortex-demenagement",
      "DisplayName": "Sortex Déménagement",
      "IsCompany": true,
      "CompanyName": "Sortex Déménagement",
      "Civility": null,
      "LastName": null,
      "FirstName": null,
      "Title": null,
      "Phone1": "04 04 04 04 04",
      "Phone2": null,
      "Fax": null,
      "Email": "contact@sortex-demenagement.fr",
      "Url": "http://www.sortex-demenagement.fr/",
      "AddressLine1": "9, Rue du Chateau",
      "AddressLine2": null,
      "PostalCode": "44000",
      "Municipality": "Nantes",
      "Country": "France",
      "Notes": null,
      "Tags": "Fournisseur"
   },
   {
      "Slug": "arnaud-berence",
      "DisplayName": "Arnaud Bérence",
      "IsCompany": false,
      "CompanyName": "Acme SA",
      "Civility": "M.",
      "LastName": "Bérence",
      "FirstName": "Arnaud",
      "Title": "Commercial",
      "Phone1": "07 07 07 07 07",
      "Phone2": null,
      "Fax": null,
      "Email": "arnaud.berence@acme.com",
      "Url": null,
      "AddressLine1": null,
      "AddressLine2": null,
      "PostalCode": null,
      "Municipality": null,
      "Country": null,
      "Notes": null,
      "Tags": "Fournisseur,Local"
   },
   {
      "Slug": "denis-agard",
      "DisplayName": "Denis Agard",
      "IsCompany": false,
      "CompanyName": null,
      "Civility": "M.",
      "LastName": "Agard",
      "FirstName": "Denis",
      "Title": null,
      "Phone1": "09 09 09 09 09",
      "Phone2": null,
      "Fax": null,
      "Email": "denisagard@live.fr",
      "Url": null,
      "AddressLine1": null,
      "AddressLine2": null,
      "PostalCode": null,
      "Municipality": null,
      "Country": null,
      "Notes": null,
      "Tags": "Prospect"
   },
   {
      "Slug": "francoise-martin",
      "DisplayName": "Françoise Martin",
      "IsCompany": false,
      "CompanyName": "Acme SA",
      "Civility": "Mme",
      "LastName": "Martin",
      "FirstName": "Françoise",
      "Title": "Directrice",
      "Phone1": "03 03 03 03 03",
      "Phone2": null,
      "Fax": null,
      "Email": "francoise.martin@acme.com",
      "Url": null,
      "AddressLine1": null,
      "AddressLine2": null,
      "PostalCode": null,
      "Municipality": null,
      "Country": null,
      "Notes": null,
      "Tags": "Fournisseur,Local"
   },
   {
      "Slug": "nadege-giorno",
      "DisplayName": "Nadège Giorno",
      "IsCompany": false,
      "CompanyName": "Sortex Déménagement",
      "Civility": "Mme",
      "LastName": "Giorno",
      "FirstName": "Nadège",
      "Title": "Secrétaire",
      "Phone1": "08 08 08 08 08",
      "Phone2": null,
      "Fax": null,
      "Email": "secretariat@sortex-demenagement.fr",
      "Url": null,
      "AddressLine1": null,
      "AddressLine2": null,
      "PostalCode": null,
      "Municipality": null,
      "Country": null,
      "Notes": null,
      "Tags": "Fournisseur"
   },
   {
      "Slug": "pierre-dupond",
      "DisplayName": "Pierre Dupond",
      "IsCompany": false,
      "CompanyName": "Acme SA",
      "Civility": "M.",
      "LastName": "Dupond",
      "FirstName": "Pierre",
      "Title": "Développeur",
      "Phone1": "01 01 01 01 01",
      "Phone2": "06 01 01 01 01",
      "Fax": null,
      "Email": "pierre.dupond@acme.com",
      "Url": "http://www.pierre-dupond.com/",
      "AddressLine1": "Les Docks",
      "AddressLine2": "BP 13",
      "PostalCode": "13000",
      "Municipality": "Marseille",
      "Country": "France",
      "Notes": "Lorem ipsum dolor sit amet, **consectetur adipiscing elit**. Sed lacus lacus, faucibus ac tincidunt non, dignissim ut quam. Maecenas non dolor euismod mi porttitor luctus. Nam at metus odio.\r\n* Ut eleifend eros quis nisl suscipit ut tincidunt libero consequat.\r\n* Mauris tincidunt, nisl vitae sodales fermentum, *libero ante luctus libero*, in vulputate mi odio at orci.\r\n* Cras ac lectus tellus, eu fringilla ante.\r\nPhasellus elementum pulvinar dolor ac pharetra. Phasellus est magna, blandit quis imperdiet ut, luctus ut nisl. Donec ligula nunc, adipiscing sit amet suscipit sit amet : http://www.euismod-a-dolor.com/.\r\nDuis interdum eros sed lorem iaculis in mollis ante vulputate. Pellentesque adipiscing nunc pretium arcu imperdiet pulvinar. Vivamus placerat@semper.mi.",
      "Tags": "Fournisseur,Local"
   },
   {
      "Slug": "richard-durand",
      "DisplayName": "Richard Durand",
      "IsCompany": false,
      "CompanyName": "Sortex Déménagement",
      "Civility": "M.",
      "LastName": "Durand",
      "FirstName": "Richard",
      "Title": "Commercial",
      "Phone1": "05 05 05 05 05",
      "Phone2": null,
      "Fax": null,
      "Email": "durand@sortex-demenagement.fr",
      "Url": null,
      "AddressLine1": null,
      "AddressLine2": null,
      "PostalCode": null,
      "Municipality": null,
      "Country": null,
      "Notes": null,
      "Tags": "Fournisseur"
   },
   {
      "Slug": "victoire-pottier",
      "DisplayName": "Victoire Pottier",
      "IsCompany": false,
      "CompanyName": null,
      "Civility": "Mme",
      "LastName": "Pottier",
      "FirstName": "Victoire",
      "Title": null,
      "Phone1": "06 06 06 06 06",
      "Phone2": null,
      "Fax": null,
      "Email": "victoirepottier@gmail.com",
      "Url": "http://www.traductions-pottier.com/",
      "AddressLine1": "12, Place de l'Escargot",
      "AddressLine2": null,
      "PostalCode": "31000",
      "Municipality": "Toulouse",
      "Country": null,
      "Notes": null,
      "Tags": "Client"
   }
]